# Generated by Django 4.1.5 on 2023-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="object_id",
            field=models.CharField(max_length=255),
        ),
    ]
