# Generated by Django 4.1.5 on 2023-03-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_dummymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dummymodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RemoveField(
            model_name="taggeditem",
            name="tag",
        ),
        migrations.AddField(
            model_name="taggeditem",
            name="tag",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_items",
                to="tags.tag",
            ),
            preserve_default=False,
        ),
    ]
