# Generated by Django 4.1.5 on 2023-03-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_alter_dummymodel_id_remove_taggeditem_tag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taggeditem",
            name="tag",
        ),
        migrations.AddField(
            model_name="taggeditem",
            name="tags",
            field=models.ManyToManyField(related_name="tagged_items", to="tags.tag"),
        ),
    ]
