# Generated by Django 4.1.5 on 2023-01-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
