name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install
            
      - name: Run tests with coverage
        env:        
          STATIC_URL: ${{ secrets.STATIC_URL }}
          MEDIA_URL: ${{ secrets.MEDIA_URL }}
          STATIC_ROOT: ${{ secrets.STATIC_ROOT }}          
          
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          SECURE_HSTS_SECONDS: ${{ secrets.SECURE_HSTS_SECONDS }}
          SECURE_SSL_REDIRECT: ${{ secrets.SECURE_SSL_REDIRECT }}
          SESSION_COOKIE_SECURE: ${{ secrets.SESSION_COOKIE_SECURE }}
          SECURE_HSTS_INCLUDE_SUBDOMAINS: ${{ secrets.SECURE_HSTS_INCLUDE_SUBDOMAINS }}
          SECURE_HSTS_PRELOAD: ${{ secrets.SECURE_HSTS_PRELOAD }}                
          
          DB_NAME_WEBWISE: ${{ secrets.DB_NAME_WEBWISE }}
          DB_USER_WEBWISE: ${{ secrets.DB_USER_WEBWISE }}
          DB_PASSWORD_WEBWISE: ${{ secrets.DB_PASSWORD_WEBWISE }}
          DB_HOST_WEBWISE: ${{ secrets.DB_HOST_WEBWISE }}
          DB_PORT_WEBWISE: ${{ secrets.DB_PORT_WEBWISE }}
        run: poetry run pytest --cov=. --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage.xml
          flags: unittests
